apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-simple-clone
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: pipelineRunId
      description: pipelineRunId unique ID
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: pathToDockerfile
      default: '.'
    - name: pipeline-debug
      default: "0"
    - name: cluster-name
      description: the name of the cluster to target
    - name: dev-cluster-namespace
      description: the namespace
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: apikey
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'bx iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: revision
      description: the branch for the git repo
  resources:
  - name: app-image
    type: image
  - name: target-cluster
    type: cluster
  tasks:
    - name: fetch-code
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
    - name: unit-tests
      runAfter: [fetch-code]
      taskRef:
        name: unit-tests-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: pipelineRunId
          value: $(params.pipelineRunId)
        - name: context
          value: tekton/ci-unit-tests
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: docker-lint-task
      runAfter: [unit-tests]
      taskRef:
        name: docker-check-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
    - name: containerize
      runAfter: [docker-lint-task]
      taskRef:
        name: containerize-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: additional-tags-script
          value: |
            # Include the clone task output variables in the environment
            source /artifacts/build.properties
            # The script is providing tag(s) as output
            # But logs can be written as error stderr
            echo "Providing an image tag including git branch and commit" >&2
            # Add a specific tag with branch and commit
            echo "${BUILD_TIMESTAMP}-${GIT_BRANCH}-${GIT_COMMIT}"          
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      resources:
        outputs:
          - name: built-image
            resource: app-image
    - name: vulnerability-advisor
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: scanReportFile
          value: 'app-image-va-report.json'
        - name: ibmcloud-api-key
          value: $(params.apikey)
        # - name: maxIteration
        #   value: '5'
        # - name: sleepTime
        #   value: '3'
        # - name: failOnScannedIssues
        #   value: 'false'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      resources:
        inputs:
          - name: image
            resource: app-image
            from:
              - containerize
    - name: deploy-dev
      taskRef:
        name: deploy-to-cluster
      runAfter: [vulnerability-advisor]
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: cluster-namespace
          value: $(params.dev-cluster-namespace)
        - name: cluster-region
          value: $(params.registry-region)
        - name: ibmcloud-api-key
          value: $(params.apikey)
        - name: allow-create-route
          value: "true"
        - name: pipeline-debug
          value: $(params.pipeline-debug)