---
inputs:
  - type: git
    branch: master
    service: ${PIPELINE_REPO}
    path: .pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    branch: master
    service: ${TEKTON_TEMP_COMMON}
    path: preview/containerize
  - type: git
    branch: master
    service: ${TEKTON_TEMP_COMMON}
    path: preview/containerize/docker
  - type: git
    branch: master
    service: ${TEKTON_TEMP_COMMON}
    path: preview/compliance-checks/unit-tests
  - type: git
    branch: master
    service: ${TEKTON_TEMP_COMMON}
    path: preview/iks
  - type: git
    branch: master
    service: ${TEKTON_TEMP_COMMON}
    path: preview/compliance-checks/vulnerability-advisor
triggers:
  - type: manual
    name: Manual Trigger
    eventListener: listener
properties:
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: imageUrl
    value: ${IMAGE_URL}
    type: text
  - name: revision
    value: master
    type: text
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: dev-cluster-namespace
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${PROD_REGION_ID}
    type: text
  - name: cluster-name
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${PROD_RESOURCE_GROUP}
    type: text
  - name: dockerconfigjson
    value: ${DOCKER_CONFIG_JSON}
    type: text
  - name: repository
    value: ${APP_REPO_FULL}
    type: text
